# -*- coding: utf-8 -*-
"""Medical_Insurance_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AMc6e7T8mZRzsTmXeExfaPcW8Np-HQcw
"""

# -*- coding: utf-8 -*-

import streamlit as st
import joblib
import numpy as np

# Page settings
st.set_page_config(page_title="Medical Insurance Prediction", page_icon="💰", layout="wide")

# Load model
model = joblib.load("Medical_regression_model.pkl")

# Title
st.markdown("<h1 style='text-align:center;color:#4CAF50;'>💰 Medical Insurance Cost Prediction</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center;'>Enter details to predict insurance premium</p>", unsafe_allow_html=True)

st.write("---")

# Sidebar Inputs
st.sidebar.header("Customer Details")

age = st.sidebar.number_input("Age", 18, 100)
diabetes = st.sidebar.selectbox("Diabetes", ["No", "Yes"])
bp = st.sidebar.selectbox("Blood Pressure Problems", ["No", "Yes"])
transplants = st.sidebar.selectbox("Any Transplants", ["No", "Yes"])
chronic = st.sidebar.selectbox("Chronic Diseases", ["No", "Yes"])
height = st.sidebar.number_input("Height (cm)")
weight = st.sidebar.number_input("Weight (kg)")
allergies = st.sidebar.selectbox("Known Allergies", ["No", "Yes"])
cancer = st.sidebar.selectbox("Family Cancer History", ["No", "Yes"])
surgeries = st.sidebar.number_input("Number of Major Surgeries", 0, 10)

# Encoding (Same as training)
diabetes = 1 if diabetes == "Yes" else 0
bp = 1 if bp == "Yes" else 0
transplants = 1 if transplants == "Yes" else 0
chronic = 1 if chronic == "Yes" else 0
allergies = 1 if allergies == "Yes" else 0
cancer = 1 if cancer == "Yes" else 0

st.write("## Customer Summary")

col1, col2, col3 = st.columns(3)

col1.metric("Age", age)
col2.metric("Height", height)
col3.metric("Weight", weight)

st.write("---")

# Prediction Button
if st.button("Predict Insurance Cost", use_container_width=True):

    input_data = np.array([[age, diabetes, bp, transplants, chronic,
                            height, weight, allergies, cancer, surgeries]])

    prediction = model.predict(input_data)

    st.write("### 💰 Predicted Premium Price")

    st.success(f"Estimated Insurance Cost: ₹ {round(prediction[0], 2)}")

    st.info("Note: This is an estimated value based on given data.")